import { chatContainerLeft } from './dom.js';

export const state = {
    lastScrollTop: chatContainerLeft ? chatContainerLeft.scrollTop : 0,
    currentMode: 'auto',
    selectedModel: localStorage.getItem('axio-selected-model') || 'deepseek',
    isGenerating: false,
    currentTurnId: null,
    historySearchInlineActive: false,
    currentViewingTools: [],
    currentViewingThoughts: [],
    currentViewingQuestions: [],
    isShowingTools: false,
    isShowingThoughts: false,
    isShowingQuestions: false,
    thoughtsExpanded: false,
    isWorkspaceActive: false,
    workspaceAutoHideTimer: null,
    currentActiveFileBalloonHtml: "",
    undoRedoFiles: [],
    currentUndoFile: null,
    currentFileDataRef: null,
    isEyeMode: false,
    currentOpenedDiff: null,
    isShowingSessionHistory: false,
    codigoDoHistoricoNoEditor: false,
    vistaDocAtual: 'chat',
    sessionHistoryList: [],
    sessionDetailCache: {},
    sessionHistoryLoaded: false,
    currentTurnLogs: [],
    currentTurnSummary: '',
    currentViewingAiResponse: '',
    suppressCol3Anim: false,
    col3OverlayCloseTimer: null,
    pendingRestore: null,
    restoreAbortController: null,
    pendingDelete: null,
    currentCheckpointId: null,
    checkpointRestoredAt: 0,
    currentSelectedHistoryGroup: null,
    currentSelectedHistoryEl: null,
    contextPopupExpanded: false,
    glossaryMatchCurrent: null,
    inspectAtivo: false,
    inspectCurrentEl: null,
    inspectLastX: 0,
    inspectLastY: 0,
    renderInspectToken: 0,
    inspectItems: [],
    inspectItemIndex: -1,
    inspectLocked: false,
    iconTooltipTimer: null,
    settingsVertexMode: false,
    settingsNavMode: false,
    settingsRevealKeys: false,
    settingsStudioApiKey: '',
    settingsVertexJsonName: '',
    settingsVertexJsonData: null,
    settingsDeepseekEnabled: false,
    settingsGeminiEnabled: false,
    attachedImages: [],
    imageCounter: 1,
    historyPreloadTimer: null,
    eventSource: null,
    restoreEvents: [],
};
